"""
Brevo SMTP email delivery for monthly audit batches.

Uses Brevo (formerly Sendinblue) transactional SMTP.
Credentials are in config/config.py BREVO section (gitignored).

NEVER log BREVO["password"].
"""

from __future__ import annotations

import logging
import mimetypes
import smtplib
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email import encoders
from datetime import date
from pathlib import Path

logger = logging.getLogger(__name__)

# Maximum total attachment size before we skip attachments and note them in body
_MAX_ATTACH_BYTES = 10 * 1024 * 1024  # 10 MB


def _is_config_missing(brevo_config: dict) -> bool:
    """Return True if the Brevo config contains placeholder values or is empty."""
    missing_keys = ("host", "user", "password", "from_address", "to_addresses")
    for key in missing_keys:
        val = brevo_config.get(key)
        if not val:
            logger.warning("Brevo config key '%s' is missing or empty — skipping email.", key)
            return True
        if isinstance(val, str) and val.strip().upper() in ("REPLACE_ME", ""):
            logger.warning(
                "Brevo config key '%s' still contains placeholder value — skipping email.",
                key,
            )
            return True
    return False


def _build_html_body(
    results: dict,  # {username: {"success": bool, "score": float|None, ...}}
    month_label: str,
    today_str: str,
    batch_dir: Path,
    attachments_skipped: bool,
) -> str:
    """Return an HTML string for the email body."""
    rows_html = ""
    for username, info in results.items():
        score = info.get("score")
        score_str = f"{score:.1f}" if score is not None else "n/a"
        trend = info.get("trend_arrow", "—")
        status = "OK" if info["success"] else "FAILED"
        status_color = "#2e7d32" if info["success"] else "#c62828"
        rows_html += (
            f"<tr>"
            f"<td>@{username}</td>"
            f"<td style='text-align:center'>{score_str}</td>"
            f"<td style='text-align:center'>{trend}</td>"
            f"<td style='text-align:center; color:{status_color}; font-weight:bold'>{status}</td>"
            f"</tr>\n"
        )

    attach_note = ""
    if attachments_skipped:
        attach_note = (
            "<p><em>Note: Report files exceed the 10 MB attachment limit and were not attached. "
            f"Retrieve them from the server at: <code>{batch_dir}</code></em></p>"
        )
    else:
        attach_note = (
            f"<p>Full reports are attached. "
            f"Server copy: <code>{batch_dir}</code></p>"
        )

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: Arial, sans-serif; color: #333; }}
  h2   {{ color: #2e5bba; }}
  table {{ border-collapse: collapse; min-width: 500px; }}
  th, td {{ border: 1px solid #ccc; padding: 8px 12px; }}
  th {{ background: #f0f4ff; font-weight: bold; }}
  tr:nth-child(even) {{ background: #fafafa; }}
</style>
</head>
<body>
<h2>Twist N Turns &mdash; Monthly Instagram Audit</h2>
<p>Audit month: <strong>{month_label}</strong> &nbsp;|&nbsp; Generated: {today_str}</p>
<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Score</th>
      <th>vs Last Month</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    {rows_html}
  </tbody>
</table>
{attach_note}
<hr>
<p style="font-size:11px; color:#888;">
  Generated by Instagram Audit Skill &mdash;
  github.com/TapasDas1982/Instagram_Audit_Skill
</p>
</body>
</html>"""


def send_batch_email(
    brevo_config: dict,
    batch_dir: Path,
    results: dict,  # {username: {"success": bool, "report_path": str|None, "score": float|None}}
    month_label: str,  # e.g. "2026-05"
) -> bool:
    """Send the monthly audit batch email via Brevo SMTP.

    Returns True on success, False on any validation or SMTP error.
    The batch run continues regardless of the return value.
    """
    if _is_config_missing(brevo_config):
        return False

    today_str = date.today().isoformat()

    # Collect report files from successful audits
    report_paths: list[Path] = []
    for info in results.values():
        if info.get("success") and info.get("report_path"):
            p = Path(info["report_path"])
            if p.exists():
                report_paths.append(p)

    # Check total size
    total_bytes = sum(p.stat().st_size for p in report_paths)
    attachments_skipped = total_bytes > _MAX_ATTACH_BYTES
    if attachments_skipped:
        logger.warning(
            "Report attachments total %.1f MB — exceeds 10 MB limit; attaching none.",
            total_bytes / (1024 * 1024),
        )

    # Compose message
    msg = MIMEMultipart("alternative" if attachments_skipped else "mixed")
    msg["Subject"] = f"Twist N Turns — Monthly IG Audit {month_label}"
    msg["From"] = brevo_config["from_address"]

    to_addresses: list[str] = brevo_config.get("to_addresses", [])
    if isinstance(to_addresses, str):
        to_addresses = [to_addresses]
    msg["To"] = ", ".join(to_addresses)

    html_body = _build_html_body(
        results, month_label, today_str, batch_dir, attachments_skipped
    )
    msg.attach(MIMEText(html_body, "html", "utf-8"))

    # Attach report files (if within size limit)
    if not attachments_skipped:
        for report_path in report_paths:
            mime_type, _ = mimetypes.guess_type(str(report_path))
            if mime_type is None:
                mime_type = "application/octet-stream"
            main_type, sub_type = mime_type.split("/", 1)
            part = MIMEBase(main_type, sub_type)
            with open(report_path, "rb") as fh:
                part.set_payload(fh.read())
            encoders.encode_base64(part)
            part.add_header(
                "Content-Disposition",
                "attachment",
                filename=report_path.name,
            )
            msg.attach(part)

    # Send via Brevo SMTP
    host: str = brevo_config["host"]
    port: int = int(brevo_config.get("port", 587))
    user: str = brevo_config["user"]
    password: str = brevo_config["password"]

    try:
        with smtplib.SMTP(host, port, timeout=30) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(user, password)
            server.send_message(msg)
        logger.info(
            "Batch email sent to %s (month=%s, reports=%d).",
            to_addresses,
            month_label,
            len(report_paths) if not attachments_skipped else 0,
        )
        return True
    except smtplib.SMTPAuthenticationError:
        logger.error(
            "SMTP authentication failed for user '%s'. "
            "Check BREVO['user'] and BREVO['password'] in config/config.py.",
            user,
        )
        return False
    except smtplib.SMTPException as exc:
        logger.error("SMTP error while sending batch email: %s", exc)
        return False
    except OSError as exc:
        logger.error("Network error connecting to Brevo SMTP (%s:%d): %s", host, port, exc)
        return False
